<?php

/**
 * @file
 * Install, update and uninstall functions for the localgov_consultations module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_install().
 *
 * Initialise state for consultations notifications and set up default blocks.
 */
function localgov_consultations_install() {
  // 1. Initialise last run state for notifications.
  $now = new DrupalDateTime('now');
  \Drupal::state()->set('localgov_consultations_process_opens_last_run', $now->getTimestamp());
  \Drupal::state()->set('localgov_consultations_process_closes_last_run', $now->getTimestamp());

  // 2. Set some default empty configs.
  $consultations_config = \Drupal::configFactory()->getEditable('localgov_consultations.templates');
  $consultations_config->set('date_changed', '')
    ->set('opened', '')
    ->set('closed', '')
    ->save();

  // 3. Define the theme to place blocks in.
  $theme = \Drupal::config('system.theme')->get('default');

  // Add Localgov Consultations Landing Banner block.
  $landing_banner = Block::load('localgov_consultations_landing_banner') ?: Block::create([
    'id' => 'localgov_consultations_landing_banner',
    'plugin' => 'localgov_consultations_landing_banner',
    'settings' => [
      'label_display' => FALSE,
    ],
  ]);
  $landing_banner->set('theme', $theme);
  $landing_banner->set('region', 'banner');
  $landing_banner->set('weight', -20);
  $landing_banner->setVisibilityConfig('request_path', [
    'id' => 'request_path',
    'negate' => FALSE,
    'pages' => '/consultations',
  ]);
  $landing_banner->save();

  // Add Localgov Consultations Page Banner.
  $page_banner = Block::load('localgov_consultations_page_banner') ?: Block::create([
    'id' => 'localgov_consultations_page_banner',
    'plugin' => 'localgov_consultations_page_banner',
    'settings' => [
      'label_display' => FALSE,
    ],
  ]);
  $page_banner->set('theme', $theme);
  $page_banner->set('region', 'banner');
  $page_banner->set('weight', -10);
  $page_banner->setVisibilityConfig('request_path', [
    'id' => 'request_path',
    'negate' => FALSE,
    'pages' => '/consultations/*',
  ]);
  $page_banner->save();
}
