<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;


/**
 * Implements hook_theme().
 */
function localgov_consultations_theme($existing, $type, $theme, $path) {
  return [
    'node__consultation' => [
      'template' => 'node--consultation',
      'base hook' => 'node',
    ],
    'node__consultation__teaser' => [
      'template' => 'node--consultation--teaser',
      'base hook' => 'node',
    ],
    'views_view__consultations' => [
      'template' => 'views-view--consultations',
      'base hook' => 'views_view',
      'path' => $path . '/templates',
    ],
    'field__node__localgov_consultation_date__consultation' => [
      'base hook' => 'field',
      'template' => 'field--node--localgov-consultation-date--consultation',
      'path' => $path . '/templates/field',
    ],
        'field__node__localgov_consultation_timeline__consultation' => [
      'base hook' => 'field',
      'template' => 'field--node--localgov-consultation-timeline--consultation',
      'path' => $path . '/templates/field',
    ],
    'paragraph__step_by_step' => [
      'template' => 'paragraph--step-by-step',
      'base hook' => 'paragraph',
      'path' => $path . '/templates/paragraphs',
    ],
  ];
}


/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FIXME: Infer based on consultations in the system, facets-style?
 */
function localgov_consultations_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['#id']) && $form['#id'] == 'views-exposed-form-consultations-page-2') {
    $options = [
      'all' => '- Any -',
      '2014' => '2014',
      '2015' => '2015',
      '2016' => '2016',
      '2017' => '2017',
      '2018' => '2018',
      '2019' => '2019',
      '2020' => '2020',
      '2021' => '2021',
      '2022' => '2022',
      '2023' => '2023',
      '2024' => '2024',
      '2025' => '2025',
      '2026' => '2026',
    ];

    $form['year'] = [
      '#title' => new TranslatableMarkup('By year'),
      '#type' => 'select',
      '#options' => $options,
      '#size' => NULL,
      '#default_value' => 'all',
    ];
  }
}

/**
 * Implements hook_preprocess_views_view().
 * @param $vars
 * @return void
 */
function localgov_consultations_preprocess_views_view(&$vars) {

  if ($vars['view']->id() == "consultations") {
    $vars['#attached']['library'][] = 'localgov_consultations/localgov_consultations';

    // Utilise localgov_base styling if available.
    $vars['#attached']['library'][] = 'localgov_base/teaser';
  }
}

/**
 * Implements hook_preprocess_node().
 * @param $variables
 * @return void
 */
function localgov_consultations_preprocess_node(&$variables) {
  $node = $variables['node'];

  if ($node->bundle() === 'consultation') {
    $variables['#attached']['library'][] = 'localgov_consultations/localgov_consultations';
  }
}

/**
 * Implements hook_preprocess_paragraphs().
 */
function localgov_consultations_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];

  if ($paragraph->bundle() === 'step_by_step') {
    $date_is_past_or_today = FALSE;

    if ($paragraph->hasField('localgov_consultation_date') && !$paragraph->get('localgov_consultation_date')->isEmpty()) {
      $date_value = $paragraph->get('localgov_consultation_date')->value;

      if ($date_value) {
        $today = date("Y-m-d");

        if ($date_value <= $today) {
          $date_is_past_or_today = TRUE;
        }
      }
    }

    $variables['date_is_past_or_today'] = $date_is_past_or_today;
  }
}

